<a href="https://colab.research.google.com/github/vakitideekshareddy-star/CSPT_ACE/blob/main/cspt_day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_excel("/content/CineMetrics_Dataset.xlsx")
df

,Movie_ID,Title,Genre,Release_Year,Duration_Min,Language,Country,Streaming_Platform,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
0,1,The Crimson Odyssey,Animation,2013,NaN,French,France,HBO Max,33.8,43.9,3.6,315.9,46.0,7.0
1,2,The Sacred Echo,Documentary,2014,88.0,Hindi,India,Prime Video,58.4,183.8,6.6,79.9,NaN,13.0
2,3,The Rising Illusion,Action,1995,105.0,Spanish,Mexico,HBO Max,12.8,13.8,6.8,71.9,32.0,30.0
3,4,The Crimson Awakening,Sci-Fi,2003,107.0,German,Germany,Netflix,11.4,27.8,8.0,74.6,81.0,33.0
4,5,The Last Legacy,Sci-Fi,2020,82.0,Hindi,India,Netflix,37.1,13.1,NaN,26.1,47.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,296,The Fading Mirage,Romance,2021,141.0,French,France,HBO Max,66.0,173.3,5.0,72.4,44.0,30.0
296,297,The Sacred Journey,Fantasy,2014,110.0,Spanish,Spain,HBO Max,43.2,52.3,3.9,252.4,53.0,32.0
297,298,The Burning Rebellion,Documentary,2006,158.0,Korean,South Korea,HBO Max,114.3,165.6,8.1,126.7,NaN,8.0
298,299,The Fading Descent,Comedy,1999,114.0,Japanese,Japan,HBO Max,188.8,661.6,5.3,132.7,41.0,25.0
299,300,The Eternal Legacy,Romance,2015,148.0,English,USA,HBO Max,9.7,0.0,6.4,121.4,63.0,20.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               285 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [3]:
df.describe()

,Movie_ID,Release_Year,Duration_Min,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
count,300.000000,300.000000,285.000000,264.000000,273.000000,282.000000,285.000000,279.000000,288.000000
mean,150.500000,2008.680000,112.564912,32.051515,83.763736,6.465957,89.589123,59.390681,19.805556
std,86.746758,8.854695,21.138048,34.471101,107.025831,1.339428,78.999020,15.403963,11.729695
min,1.000000,1995.000000,70.000000,2.100000,0.000000,3.200000,5.000000,25.000000,0.000000
25%,75.750000,2001.000000,98.000000,12.800000,22.600000,5.600000,26.500000,48.000000,10.750000
50%,150.500000,2009.000000,112.000000,22.100000,51.900000,6.450000,69.600000,59.000000,20.000000
75%,225.250000,2016.250000,127.000000,38.450000,109.900000,7.400000,128.200000,70.000000,30.000000
max,300.000000,2024.000000,166.000000,300.000000,906.000000,9.700000,413.800000,100.000000,40.000000

In [4]:
df.head()

,Movie_ID,Title,Genre,Release_Year,Duration_Min,Language,Country,Streaming_Platform,Budget_Million_USD,Revenue_Million_USD,IMDB_Rating,Votes_Thousands,Critic_Score,Director_Experience_Years
0,1,The Crimson Odyssey,Animation,2013,NaN,French,France,HBO Max,33.8,43.9,3.6,315.9,46.0,7.0
1,2,The Sacred Echo,Documentary,2014,88.0,Hindi,India,Prime Video,58.4,183.8,6.6,79.9,NaN,13.0
2,3,The Rising Illusion,Action,1995,105.0,Spanish,Mexico,HBO Max,12.8,13.8,6.8,71.9,32.0,30.0
3,4,The Crimson Awakening,Sci-Fi,2003,107.0,German,Germany,Netflix,11.4,27.8,8.0,74.6,81.0,33.0
4,5,The Last Legacy,Sci-Fi,2020,82.0,Hindi,India,Netflix,37.1,13.1,NaN,26.1,47.0,15.0

In [5]:
df.shape

(300, 14)

In [6]:
df.isnull().sum()

Movie_ID                      0
Title                         0
Genre                        12
Release_Year                  0
Duration_Min                 15
Language                      9
Country                       0
Streaming_Platform            9
Budget_Million_USD           36
Revenue_Million_USD          27
IMDB_Rating                  18
Votes_Thousands              15
Critic_Score                 21
Director_Experience_Years    12
dtype: int64

In [10]:
df["Duration_Min"] = df["Duration_Min"].fillna(df["Duration_Min"].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Movie_ID                   300 non-null    int64
 1   Title                      300 non-null    object
 2   Genre                      288 non-null    object
 3   Release_Year               300 non-null    int64
 4   Duration_Min               300 non-null    float64
 5   Language                   291 non-null    object
 6   Country                    300 non-null    object
 7   Streaming_Platform         291 non-null    object
 8   Budget_Million_USD         264 non-null    float64
 9   Revenue_Million_USD        273 non-null    float64
 10  IMDB_Rating                282 non-null    float64
 11  Votes_Thousands            285 non-null    float64
 12  Critic_Score               279 non-null    float64
 13  Director_Experience_Years  288 non-null    float64
dtypes: float64(7), int64(2), object(5)
memory usage: 32.9+ KB

In [11]:
df[numeric_cols].isnull().sum()

Duration_Min                  0
Budget_Million_USD           36
Revenue_Million_USD          27
IMDB_Rating                  18
Votes_Thousands              15
Critic_Score                 21
Director_Experience_Years    12
dtype: int64

In [12]:
df.isnull().sum()

Movie_ID                      0
Title                         0
Genre                        12
Release_Year                  0
Duration_Min                  0
Language                      9
Country                       0
Streaming_Platform            9
Budget_Million_USD           36
Revenue_Million_USD          27
IMDB_Rating                  18
Votes_Thousands              15
Critic_Score                 21
Director_Experience_Years    12
dtype: int64

In [13]:
before_rows = df.shape[0]
before_rows

300

In [18]:
df = df.dropna()

In [19]:
after_rows = df.shape[0]
print('Rows before:', before_rows)
print('Rows after: ', after_rows)
print('Dropped:    ', before_rows - after_rows)

Rows before: 300
Rows after:  168
Dropped:     132